In [1]:
import numpy as np

In [2]:
array_of_zeros_int = np.zeros((4,5),dtype = np.int16)
array_zeros_int

NameError: name 'array_zeros_int' is not defined

In [4]:
array_of_zeros_int = np.zeros((4,5))
array_of_zeros_int = np.zeros((4,5),dtype = np.int16)
array_zeros_int

NameError: name 'array_zeros_int' is not defined

In [5]:
array_of_zeros_int = np.zeros((4,5))
array_of_zeros_int

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
array_of_zeros_int = np.zeros((4,5),dtype = np.int16)
array_of_zeros_int

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [11]:
arra_2d = np.array([(2,4,6),(3,5,7)])
arra_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [13]:
arra_2d.shape

(2, 3)

In [14]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [16]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [18]:
a+b

array([15, 15, 15])

In [19]:
a-b

array([5, 5, 5])

In [20]:
a*b

array([50, 50, 50])

In [21]:
a/b

array([2., 2., 2.])

In [22]:
a<50

array([ True,  True,  True])

In [23]:
b>100

array([False, False, False])

In [24]:
#dot function or method

In [25]:
A = np.array([[1,2],[0,1]])
B = np.array([[2,0],[2,3]])

print('A:\n',A)
print('B:\n',B)

A:
 [[1 2]
 [0 1]]
B:
 [[2 0]
 [2 3]]


In [26]:
A*B

array([[2, 0],
       [0, 3]])