In [1]:
import numpy as np 

In [8]:
numbers = [10,9,8,7]
array_one = np.array(numbers)

array_one

array([10,  9,  8,  7])

In [9]:
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
array_of_fives = np.fives((6,7))
array_of_fives

AttributeError: module 'numpy' has no attribute 'fives'

In [11]:
array_of_ones = np.ones((4,5))
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
array_of_twos = np.twos((4,5))
array_of_twos

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#print even number from 1-50

In [15]:
array_of_even = np.arange(2,50,2)
array_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [16]:
#print odd number from 1-50

In [17]:
array_of_odd = np.arange(1,50,2)
array_of_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [18]:
#creating an array of 2 dimensions

In [19]:
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [20]:
array_2d.shape

(2, 3)