In [1]:
import numpy as np

In [2]:
#introduction to iterating with numpy arrays : 

In [3]:
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [5]:
#iteration over the rows 

In [6]:
students = np.array([['ravi','faiyaz','shankar','chinmay'],
                    [65,56,78,99],
                    [71,82,79,92]])

In [7]:
for i in students:
    print('i=',i)

i= ['ravi' 'faiyaz' 'shankar' 'chinmay']
i= ['65' '56' '78' '99']
i= ['71' '82' '79' '92']


In [8]:
flipkart_customers = np.array([['shaik','bhabani','rajgopal','veena'],
                              [65,56,78,99],
                              [71,82,79,92]])

In [9]:
for elements in flipkart_customers.flatten():
    print(elements)

shaik
bhabani
rajgopal
veena
65
56
78
99
71
82
79
92


In [10]:
for x in flipkart_customers.flatten(order = 'F'):
    print(x)

shaik
65
71
bhabani
56
82
rajgopal
78
79
veena
99
92


In [11]:
#introduction to nditer

In [12]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
for i in np.nditer(x,order= 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [16]:
for i in np.nditer (x,order = 'F', flags = ['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
